/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StorefrontConfig } from './storefrontConfig';
import { ZohoConfig } from './zohoConfig';


export interface Integrations {
    Zoho?: ZohoConfig;
    Storefront?: StorefrontConfig;
}
