/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaWithFacets } from './metaWithFacets';
import { SupplierProduct } from './supplierProduct';


export interface ListSupplierProduct {
    Items?: Array<SupplierProduct>;
    Meta?: MetaWithFacets;
}
