/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdminUser } from './adminUser';
import { Meta } from './meta';


export interface ListAdminUser {
    Items?: Array<AdminUser>;
    Meta?: Meta;
}
