/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShipmentDestinationAddress } from './shipmentDestinationAddress';
import { ShipmentOriginAddress } from './shipmentOriginAddress';


export interface ShipmentRateQuote {
    CarrierName?: string;
    CarrierSCAC?: string;
    CarrierGuarantee?: string;
    CarrierTransitDays?: number;
    Origin?: ShipmentOriginAddress;
    Destination?: ShipmentDestinationAddress;
    TotalCharge?: number;
    BaseCharge?: number;
    MinimumCharge?: number;
    FuelCharge?: number;
    FuelSurcharge?: number;
    AccessorialCharge?: number;
    Discount?: number;
    ExpirationDate?: Date;
    PickupAppointmentDate?: string;
    PickupAppointmentStart?: string;
    PickupAppointmentEnd?: string;
    DeliveryAppointmentEnd?: string;
    DeliveryAppointmentDate?: string;
    DeliveryAppointmentStart?: string;
}
