/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cost } from './cost';
import { Equipment } from './equipment';
import { Item } from './item';
import { Stop } from './stop';


export interface ShipmentStatus {
    Status?: string;
    CarrierName?: string;
    RequestedPickUpDate?: string;
    RequestedDeliveryDate?: string;
    EstimatedDeliveryDate?: string;
    PickUpDate?: string;
    DeliveryDate?: string;
    TotalCost?: number;
    TotalWeight?: number;
    CubicSize?: number;
    PalletQuantity?: number;
    PalletType?: string;
    PalletStackable?: boolean;
    SkidSpotQuantity?: number;
    UnitOfWeight?: any;
    BolNumber?: string;
    OrderNumber?: string;
    PoNumber?: string;
    ProNumber?: string;
    PodSignature?: string;
    GlCode?: string;
    CustomerNotes?: string;
    ShipmentNotes?: any;
    AsnNotification?: any;
    Stops?: Array<Stop>;
    Items?: Array<Item>;
    References?: Array<any>;
    Costs?: Array<Cost>;
    Equipment?: Equipment;
}
