/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShipmentRate } from './shipmentRate';
import { ShipmentRateQuote } from './shipmentRateQuote';


export interface ShipmentRateQuoteLog {
    id?: string;
    timeStamp?: Date;
    customerId?: string;
    RateRequest?: ShipmentRate;
    Items?: Array<ShipmentRateQuote>;
}
