/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupplierPriceBreak } from './supplierPriceBreak';


export interface SupplierPriceSchedule {
    ID?: string;
    Name?: string;
    ApplyTax?: boolean;
    ApplyShipping?: boolean;
    MinQuantity?: number;
    MaxQuantity?: number;
    UseCumulativeQuantity?: boolean;
    RestrictedQuantity?: boolean;
    PriceBreaks?: Array<SupplierPriceBreak>;
}
