export * from './adminUser.service';
import { NetFxAdminUserService } from './adminUser.service';
export * from './billingAddress.service';
import { NetFxBillingAddressService } from './billingAddress.service';
export * from './customer.service';
import { NetFxCustomerService } from './customer.service';
export * from './customerUser.service';
import { NetFxCustomerUserService } from './customerUser.service';
export * from './shipment.service';
import { NetFxShipmentService } from './shipment.service';
export * from './shipmentBlindAddress.service';
import { NetFxShipmentBlindAddressService } from './shipmentBlindAddress.service';
export * from './shipmentDestinationAddress.service';
import { NetFxShipmentDestinationAddressService } from './shipmentDestinationAddress.service';
export * from './shipmentItem.service';
import { NetFxShipmentItemService } from './shipmentItem.service';
export * from './shipmentOriginAddress.service';
import { NetFxShipmentOriginAddressService } from './shipmentOriginAddress.service';
export * from './shipmentRate.service';
import { NetFxShipmentRateService } from './shipmentRate.service';
export * from './shippingAddress.service';
import { NetFxShippingAddressService } from './shippingAddress.service';
export * from './user.service';
import { NetFxUserService } from './user.service';
export * from './auth.service';
import { NetFxAuthService } from './auth.service';
export * from './token.service';
import { NetFxTokenService } from './token.service';
export const APIS = [NetFxAdminUserService, NetFxBillingAddressService, NetFxCustomerService, NetFxCustomerUserService, NetFxShipmentService, NetFxShipmentBlindAddressService, NetFxShipmentDestinationAddressService, NetFxShipmentItemService, NetFxShipmentOriginAddressService, NetFxShipmentRateService, NetFxShippingAddressService, NetFxUserService, NetFxAuthService, NetFxTokenService];
